name: de-estudiante-a-desarrollador-y-a-trabajador
md: 
published: true
published_at: "2026-06-28T16:15:18Z"
sha256: "d9b2e6c464e624dfba48ccb3768a78a2b3183f33d4ff7df2dad17caa37d4abd9"
republish: false
